package human.com.code20220913;

public class homework2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.print("안녕자바");
		System.out.println(" ");

		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");

		System.out.println(" ");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");

		System.out.println(" ");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print("*");
		System.out.println(" ");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");

		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("\t");
		System.out.print("성적표");
		System.out.print("\t");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("국어");
		System.out.print("\t");
		System.out.print("50");
		System.out.print("\t");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("영어");
		System.out.print("\t");
		System.out.print("50");
		System.out.print("\t");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("수학");
		System.out.print("\t");
		System.out.print("50");
		System.out.print("\t");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("컴퓨터 학과");
		System.out.print(" ");
		System.out.print(" ");
		System.out.print(" ");

		System.out.print("홍길동");
		System.out.print("*");
		System.out.println(" ");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.print("*");
		System.out.println(" ");

		System.out.println(" ");
		System.out.print("일");
		System.out.print("\t");
		System.out.print("월");
		System.out.print("\t");
		System.out.print("화");
		System.out.print("\t");
		System.out.print("수");
		System.out.print("\t");
		System.out.print("목");
		System.out.print("\t");
		System.out.print("금");
		System.out.print("\t");
		System.out.print("토");
		System.out.print("\t");
		System.out.println(" ");
		System.out.print("1");
		System.out.print("\t");
		System.out.print("2");
		System.out.print("\t");
		System.out.print("3");
		System.out.print("\t");
		System.out.print("4");
		System.out.print("\t");
		System.out.print("5");
		System.out.print("\t");
		System.out.print("6");
		System.out.print("\t");
		System.out.print("7");
		System.out.print("\t");
		System.out.println(" ");
		System.out.print("8");
		System.out.print("\t");
		System.out.print("9");
		System.out.print("\t");
		System.out.print("10");
		System.out.print("\t");
		System.out.print("11");
		System.out.print("\t");
		System.out.print("12");
		System.out.print("\t");
		System.out.print("13");
		System.out.print("\t");
		System.out.print("14");
		System.out.print("\t");
		System.out.println(" ");
		System.out.print("15");
		System.out.print("\t");
		System.out.print("16");
		System.out.print("\t");
		System.out.print("17");
		System.out.print("\t");
		System.out.print("18");
		System.out.print("\t");
		System.out.print("19");
		System.out.print("\t");
		System.out.print("20");
		System.out.print("\t");
		System.out.print("21");
		System.out.print("\t");
		System.out.println(" ");
		System.out.print("22");
		System.out.print("\t");
		System.out.print("23");
		System.out.print("\t");
		System.out.print("24");
		System.out.print("\t");
		System.out.print("25");
		System.out.print("\t");
		System.out.print("26");
		System.out.print("\t");
		System.out.print("27");
		System.out.print("\t");
		System.out.print("28");
		System.out.print("\t");
		System.out.println(" ");
		System.out.print("29");
		System.out.print("\t");
		System.out.print("30");
		System.out.print("\t");
		System.out.print("31");
		System.out.print("\t");
	}

}
